# Generated by Django 3.1.7 on 2021-10-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='party',
        ),
        migrations.AlterField(
            model_name='leader',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='nishan',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
