# Generated by Django 3.1.7 on 2021-10-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_poll', '0002_auto_20211003_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_sound', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
